#!/bin/bash

# This script is intended to print "Hello, Bash!" and a special pattern
MAX_NO=0
echo -n "Enter a number between 5 and 9: "
read MAX_NO
if ! [ $MAX_NO -ge 5 -a $MAX_NO -le 9 ] ; then
    echo "You entered a value out of range, try again."
    exit 1
fi
clear
for (( i=1; i<=MAX_NO; i++)) 
    do
        for (( s=MAX_NO; s>=i; s-- ))
            do
                echo -n " " 
            done
        for (( j=1; j<=i;  j++ ))
            do
                echo -n " ."
            done
        echo ""
    done
for (( i=MAX_NO - 1; i>=1; i--)) 
    do
        for (( s=MAX_NO; s>=i; s-- ))
            do
                echo -n " " 
            done
        for (( j=1; j<=i;  j++ ))
            do
                echo -n " ."
            done
        echo ""
    done
printf "\n--------------------------
        \nWelcome to Bash Scripting!
        \n--------------------------\n"
