#!/opt/homebrew/bin/bash

# ---- configuration settings for your zet --------
EDITOR=vim
PUBLIC=$HOME/documents/repos/zettelkasten-public
PRIVATE=$HOME/documents/private/zettelkasten-private
OPTION=$PUBLIC

# ---- commands for zet ------
x_isomin() { date -u +%Y%m%d%H%M ; }

x_dir() {
  local dir="$OPTION"
  mkdir -p "$dir" && echo "$dir"
}

x_all() {
    local dir="$(x_dir)"
    ls $dir | grep -v '.md'
}

x_create() {
  local title="$*"
  local dir readme
  dir="$(x_dir)/$(x_isomin)"
  readme="$dir/README.md"
  mkdir -p "$dir"
  printf "# %s\n\n" "$title" > "$readme"
  "$EDITOR" "$readme"
  cd "$dir" &>/dev/null
  [[ -s "$dir/README.md" ]] || return 1
  line=$(head -1 "$dir/README.md" | sed 's/#\+ *//')
  test -n "$line"
  echo "Committing: $line"
  #git add -A "$dir" &>/dev/null
  #git commit -m "$line" &>/dev/null
  #git push &>/dev/null
}

x_find() {
    local dir="$(x_dir)"
    readarray -t arr <<< "$(x_all)"
    for i in "${arr[@]}"; do
        # TODO: parse the README file and check if the find option
        # exists in the last line -> if it does, add that file to the output
        cat $dir/$i/README.md
    done
}

# ---- handling command line args ---------
while IFS= read -r line; do
  [[ $line =~ ^declare\ -f\ x_ ]] || continue
  COMMANDS+=( "${line##declare -f x_}" )
done < <(declare -F)
mapfile -t COMMANDS < \
  <(LC_COLLATE=C sort < <(printf "%s\n" "${COMMANDS[@]}"))

if [[ -n "$1" ]]; then
  if [ "$1" = "--private" -o "$1" = "-p" ]; then
    OPTION=$PRIVATE
    shift 1
  fi
  declare CMD="$1"; shift
  for c in "${COMMANDS[@]}"; do
    if [[ $c == "$CMD" ]]; then
      "x_$CMD" "$@"
      exit $?
    fi
  done
fi
